name: 'GitHub Push'
description: 'Pushing to GitHub repository local changes'
author: 'JangGyeongSik/build-tet'
branding:
  icon: upload-cloud
  color: green
inputs:
  github_token:
    description: 'GitHub token or PAT token'
    required: true
    default: ${{ github.gyeongsik_secret }}
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: 'JangGyeongSik/build-tet'
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
  force:
    description: 'Determines if force push is used'
    required: false
  tags:
    description: 'Determines if --tags is used'
    required: false
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'
runs:
  using: 'node12'
  main: 'start.js'