apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: argocd-frontendconfig
  #namespace: argocd 
spec:
  sslPolicy: gcp-tet-ssl-policy
  redirectToHttps:
    enabled: true
    responseCodeName: "301"


