apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: dev-gyeongsik-certificate
  #namespace add 
  #namespace: argocd
spec:
  domains:
    - argocd.stan-gyeong.shop
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: gke-gyeongsik-argocd
    #Associate the ingress with the certificate name
    networking.gke.io/managed-certificates: dev-gyeongsik-certificate
    networking.gke.io/v1beta1.FrontendConfig: argocd-frontendconfig
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
spec:
  rules:
    - host: argocd.stan-gyeong.shop
      http:
        paths:
          - path: /*
            backend:
              serviceName: argocd-server-external
              servicePort: http

    