apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: prd-backend-config
  namespace: {{ .Values.name }}
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 3
    type: HTTP
    requestPath: /*
    port: 8080
  logging:
    enable: true
    sampleRate: 1.0
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 60
