apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prd-nginx-certificate
  namespace: {{ .Values.name }}
spec:
  domains:
  # Replace the value with your domain name
  - prd-nginx.gyeongsik-tet.shop