#apiVersion: apps/v1
#kind: Deployment
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx 
  namespace: {{ .Values.name }}
  labels:
    app: prd-nginx 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prd-nginx 
      name: nginx 
  template:
    metadata:
      labels:
        name: nginx 
        app: prd-nginx 
    spec:
      #initContainers:
      #  - name: clone
      #    image: alpine/git:latest
      #    {{- with .Values.initCommand }}
      #    command:
      #      {{- toYaml . | nindent 10 }}
      #    {{- end }}
      #imagePullSecrets:
      #- name: {{ .Values.imagePullSecrets }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: rollout-demo
          ports:
            - containerPort: 8080
      #     volumeMounts:
      #     - name: storage-clone 
      #       mountPath: "/root/last_modify"
      #     lifecycle:
      #       postStart:
      #         exec:
      #           {{- with .Values.postStartCommand }}
      #           command:
      #             {{- toYaml . | nindent 18 }}
      #           {{- end }}
      # volumes:
      # - name: storage-clone
      #   emptyDir: {}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}  
      terminationGracePeriodSeconds: 30
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.nodepool }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - app-pool
  strategy:
    blueGreen:
      activeService: rollout-bg-active 
      previewService:  rollout-bg-preview 
      autoPromotionEnabled: true  

      