apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: argo-rollouts
  namespace: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: argo-rollouts
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prservice.name }}
  labels:
    app: argo-rollouts
  namespace: {{ .Values.name }}
spec:
  type: {{ .Values.prservice.type }}
  ports:
    - port: {{ .Values.prservice.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: argo-rollouts