apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tomcat 
  namespace: {{ .Values.name }}
  labels:
    app: nginx-tomcat 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx-tomcat 
      name: nginx-tomcat 
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nginx-tomcat 
        app: nginx-tomcat 
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
      containers:
        - image: kqkdn1/tomcat_mariadb:nginx_tomcat
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: nginx-tomcat
          ports:
            - containerPort: 80
              name: http
              protocol: TCP 
        #resources:
        #  requests:
        #    memory: {{ .Values.requestsMemory | quote }}
        #    cpu: {{ .Values.requestsCpu | quote }}
        #  limits:
        #    memory: {{ .Values.limitsMemory | quote }}
        #    cpu: {{ .Values.limitsCpu | quote }}
      terminationGracePeriodSeconds: 30
