apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tomcat 
  namespace: {{ .Values.name }}
  labels:
    app: nginx-tomcat 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  hostAliases:
  - ip: 34.64.186.194
    hostnames:
    - "codeserver.gyeongsik-tet.shop"
  nodeSelector:
    cloud.google.com/gke-nodepool: {{ .Values.nodepool }}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx-tomcat 
      name: nginx-tomcat 
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nginx-tomcat 
        app: nginx-tomcat 
    spec:
      initContainers:
        - name: clone
          image: alpine/git:latest
          {{- with .Values.initCommand }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      #imagePullSecrets:
      #- name: {{ .Values.imagePullSecrets }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: nginx-tomcat
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /health_check.txt
              port: 80
              scheme: HTTP
            initialDelaySeconds: 100
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health_check.txt
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health_check.txt
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 5
          lifecycle:
            postStart:
              exec:
                {{ with .Values.postStartCommand }}
                command:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
            preStop:
              exec:
                {{- with .Values.preStopCommand }}
                command:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
        #resources:
        #  requests:
        #    memory: {{ .Values.requestsMemory | quote }}
        #    cpu: {{ .Values.requestsCpu | quote }}
        #  limits:
        #    memory: {{ .Values.limitsMemory | quote }}
        #    cpu: {{ .Values.limitsCpu | quote }}
      terminationGracePeriodSeconds: 30
