apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx 
  namespace: {{ .Values.name }}
  labels:
    app: nginx 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: {{ .Values.nodepool }}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx 
      name: nginx 
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nginx 
        app: nginx 
    spec:
      initContainers:
        - name: clone
          image: alpine/git:latest
          {{- with .Values.initCommand }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
      #imagePullSecrets:
      #- name: {{ .Values.imagePullSecrets }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: nginx
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                {{ with .Values.postStartCommand }}
                command:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
            preStop:
              exec:
                {{- with .Values.preStopCommand }}
                command:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
        #resources:
        #  requests:
        #    memory: {{ .Values.requestsMemory | quote }}
        #    cpu: {{ .Values.requestsCpu | quote }}
        #  limits:
        #    memory: {{ .Values.limitsMemory | quote }}
        #    cpu: {{ .Values.limitsCpu | quote }}
      terminationGracePeriodSeconds: 30
