apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-tomcat 
  namespace: dev-{{ .Values.name }}
  labels:
    app: dev-tomcat 
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: dev-tomcat 
      name: nginx-tomcat 
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nginx-tomcat 
        app: dev-tomcat 
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: nginx-tomcat
        ports:
          - containerPort: 80
            name: http
            protocol: TCP 
        resources:
          requests:
            memory: {{ .Values.requestsMemory | quote }}
            cpu: {{ .Values.requestsCpu | quote }}
          limits:
            memory: {{ .Values.limitsMemory | quote }}
            cpu: {{ .Values.limitsCpu | quote }}
