apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: dev-frontend-config
  namespace: {{ .Values.name }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT